[package]
name = "flight-client"
version = "0.1.0"
description = "Apache Arrow Flight client for node.js"
authors = ["robstar.pack@gmail.com"]
license = "MIT"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow-flight = { version = "46", extras = ["flight-sql"] }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
